[package]
name = "RustSQL"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.20.0", features = ["v4", "serde"] }
